# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
rss: /atom.xml

since: 2015

# Set default keywords (Use a comma to separate)
keywords: "SharePoint, Office365, Azure, JavaScript, Typescript, Powershell"

# Put your favicon.ico into `hexo-site/themes/hiero/source/` directory.
favicon: css/images/favicon.ico


# Put your avatar.jpg into `hexo-site/themes/hiero/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar: 
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg
  

# AboutPage background
# about_big_image: [gallery/backgroud/4436335-wallpapers.jpg, gallery/backgroud/4436402-wallpapers.jpg, gallery/backgroud/4436335-wallpapers.jpg, gallery/backgroud/4436674-wallpapers.jpg, gallery/backgroud/4436285-wallpapers.jpg, gallery/backgroud/4436507-wallpapers.jpg, gallery/backgroud/4436278-wallpapers.jpg, gallery/backgroud/4436140-wallpapers.jpg, gallery/backgroud/4436054-wallpapers.jpg, gallery/backgroud/4436843-wallpapers.jpg, gallery/backgroud/4436228-wallpapers.jpg, gallery/backgroud/4436464-wallpapers.jpg, gallery/backgroud/4436430-wallpapers.jpg, gallery/backgroud/4436454-wallpapers.jpg]
about_big_image: []


# Homepage thumbnail
random_thumb: false


# Post Article's Content
post_catalog:
  enable: true


# Content
fancybox: true

share:
  facebook: true
  twitter: true
  linkedin: true
  google: true
  email: true

# Sidebar
sidebar: right
widgets:
- search
- social
- recent_posts
- tagcloud

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  title: Dario Alvarez
  description: My full name is <strong class="post_share_full_name">Dario Alejandro Alvarez Borrero</strong>, I'm a software developer from Venezuela/Spain and currently living in London. I work at Content and Code as a Office 365 / Azure.
  avatar: /gallery/avatar/dario_alvarez-150x150.jpg
  twitter: darius231
  links:
    Github: https://github.com/darius231/
    Twitter: https://twitter.com/darius231/
    Facebook: https://www.facebook.com/dalvarezborrero
    Google-plus: https://plus.google.com/110601997919183679297
    Instagram: https://www.instagram.com/darius231/
    linkedin: https://www.linkedin.com/in/darius231/
    email: dario17231@gmail.com

    # https://www.w3schools.com/colors/colors_picker.asp
skills:
  SharePoint:
    image: /gallery/skills/skill-sharepoint.png
    statback: 67aae4
    statpack: 2172B9
    statlevel: 97
  HTML5:
    image: /gallery/skills/skill-html.png
    statback: eeb5aa
    statpack: DB634C
    statlevel: 95
  TypeScript:
    image: /gallery/skills/skill-typescript.png
    statback: 4db8ff
    statpack: 007ACC
    statlevel: 95
  PowerShell:
    image: /gallery/skills/skill-powershell.png
    statback: 7fb6e6
    statpack: 277DC9
    statlevel: 90
  JavaScript:
    image: /gallery/skills/skill-javascript.png
    statback: ffdb66
    statpack: EDB600
    statlevel: 90
  NodeJS:
    image: /gallery/skills/skill-node.png
    statback: c0e19d
    statpack: 8CC84B
    statlevel: 90
  "Office 365":
    image: /gallery/skills/skill-o365.png
    statback: fe7d4d
    statpack: DA3A01
    statlevel: 90
  "Visual Studio Code":
    image: /gallery/skills/skill-vscode.png
    statback: 4db7fe
    statpack: 0179CB
    statlevel: 90
  React:
    image: /gallery/skills/skill-react.png
    statback: cdf3fe
    statpack: 61DAFB
    statlevel: 85
  CSS3:
    image: /gallery/skills/skill-css.png
    statback: 9dc7e2
    statpack: 3C8FC4
    statlevel: 80
  Azure:
    image: /gallery/skills/skill-azure.png
    statback: 5ea3ed
    statpack: 1566BF
    statlevel: 80
  "C#":
    image: /gallery/skills/skill-c-sharp.png
    statback: 80bdff
    statpack: 007AFF
    statlevel: 80
  Gulp:
    image: /gallery/skills/skill-gulp.png
    statback: f7baba
    statpack: EB4A4B
    statlevel: 75
  Git:
    image: /gallery/skills/skill-git.png
    statback: f8ada0
    statpack: EF4F32
    statlevel: 75
  Angular:
    image: /gallery/skills/skill-angular.png
    statback: ff4d73
    statpack: DD0031
    statlevel: 70
  
# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname:
disqus_shortname: js231sharepoint 
livere_shortname:
uyan_uid: 
wumii:
gitment:
  owner: DariuS231                   #Your GitHub ID
  repo:                    #The repo to store comments
  client_id:               #Your client ID
  client_secret:           #Your client secret

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night eighties



# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
  - category
  - tagcloud
  - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:
baidu_site_verification:
qihu_site_verification:

# Miscellaneous
google_analytics: UA-71197602-1
gauges_analytics:
baidu_analytics:
tencent_analytics:
busuanzi_analytics: false
twitter: Darius231
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 1260716016

# donation button
donate:
    enable: false
    message: ''
    wechatImage: 
    alipayImage: 

# Automatic page load progress bar by PACE.js
progressBar:
  enable: true #switch
  themeCSS: https://cdn.rawgit.com/HubSpot/pace/4afddfb3/themes/orange/pace-theme-flash.css    #PATH to PACE theme CSS, support relative / absolute path

# Ad
ad:
  google_adsense_ad_client_id: 